### ISSUE TITLE
I cant make another file

### ISSUE THREAD

**Issue by fortnite2015** [educ8s/Raylib-CPP-Starter-Template-for-VSCODE-V2#3]
When I make another file and try to run the file it says "launch program does not exist" how can i make a another file for my own projects?

**Comment by mmmovania** [comment]
The makefile that this repo gives only includes main.c. You need to ensure all .cpp files are included but that is missing in the makefile.

A similar issue was raised in v1 repo and I shared the makefile that I use. Please see this: https://github.com/educ8s/Raylib-CPP-Starter-Template-for-VSCODE/issues/3

See if this helps.
