### ISSUE TITLE
Trojan virus detected on windows after unzipping

### ISSUE THREAD

**Issue by BMatulonis** [educ8s/Raylib-CPP-Starter-Template-for-VSCODE-V2#4]
After downloading and unzipping, Windows Defender immediately caught a virus within the folder... V1 seems to be fine so far though

**Comment by Adrakaris** [comment]
Nothing in there seems to be malicious (and windows defender said nothing for me), you should be able to see what specific file it has quarantined though if it has detected a virus. Perhaps that would be more helpful.

**Comment by educ8s** [comment]
No virus here.
